<script setup lang="ts">
import {Head,Link,router} from '@inertiajs/vue3';
import StoreLayout from '../Layouts/StoreLayout.vue';
const props = defineProps<{items:any[],total:number}>();
const discountTotal = () => props.items.reduce((sum:number, item:any) => sum + (item.discount_total || 0), 0);
const asset = (url?:string) => !url ? '' : url.startsWith('http') ? url : `/storage/${url}`;
const itemImage = (item:any) => asset(item.variant.product.media?.find((media:any) => media.type === 'image')?.url || item.variant.product.image_url);
const setVariant = (item:any, variantId:number) => router.put(`/cart/${item.variant.id}/variant`, {variant_id:variantId}, {preserveScroll:true});
</script>
<template><Head title="Кошик"/><StoreLayout><section class="narrow cart-page"><h1>Кошик</h1><div v-if="!items.length" class="empty">Кошик поки порожній. <Link href="/">До каталогу</Link></div><article v-for="item in items" :key="item.variant.id" class="cart-row"><img :src="itemImage(item)" :alt="item.variant.product.name"><div><b>{{item.variant.product.name}}</b><label class="cart-size">Довжина<select :value="item.variant.id" @change="setVariant(item, Number(($event.target as HTMLSelectElement).value))"><option v-for="variant in item.variant.product.variants" :key="variant.id" :value="variant.id" :disabled="!variant.is_active || variant.stock_on_hand <= variant.stock_reserved">{{variant.name}}</option></select></label><p>{{item.quantity}} шт. · {{item.variant.sku}}</p></div><div class="discounted-price"><span v-if="item.discount_total" class="discount-label">-{{item.variant.discount_percentage}}%</span><del v-if="item.discount_total">{{(item.original_total/100).toLocaleString('uk-UA')}} ₴</del><b>{{(item.total/100).toLocaleString('uk-UA')}} ₴</b></div><button class="link" @click="router.delete(`/cart/${item.variant.id}`)">Видалити</button></article><div v-if="items.length && discountTotal()" class="cart-discount-total"><span>Ваша знижка</span><b>− {{(discountTotal()/100).toLocaleString('uk-UA')}} ₴</b></div><div v-if="items.length" class="total"><span>Разом</span><b>{{(total/100).toLocaleString('uk-UA')}} ₴</b></div><Link v-if="items.length" href="/checkout" class="button">Оформити замовлення</Link></section></StoreLayout></template>
